config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :products, only: [:index, :show]

  namespace :admin do
    root 'products#index' 
    resources :products do
      member do
        delete :destroy_image
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  # validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :sku , presence: true, uniqueness: true
  validates :list_price, :sell_price, :quantity, presence: true, numericality: { greater_than: 0 }
  validate :list_price_greater_than_sell_price?

  # relationships
  has_many_attached :images

  enum status: [:on_sell, :off_sell, :restocking]

  #scope
  scope :sort_by_created_at, -> { order('created_at DESC') }
  scope :sort_by_column, ->(order_by, direction) { order("#{order_by} #{direction}") }
  scope :available, -> { where.not(status: 'off_sell').where('list_price > 0') }

  private

  def list_price_greater_than_sell_price?
    return if (list_price && sell_price).nil?

    errors.add :sell_price, '必須大於 sell_price' if list_price < sell_price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :permission_check!

  layout 'backend'

  def index
    return @products = Product.with_attached_images.sort_by_column(params[:order_by], params[:direction]) if params[:order_by]

    @products = Product.sort_by_created_at
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: '新增完成'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to edit_admin_product_path(@product), notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: '刪除成功'
  end

  def destroy_image
    image_blob = ActiveStorage::Attachment.find(params[:id])
    image_blob.purge_later
    redirect_back(fallback_location: edit_admin_product_path)
  end

  private

  def find_product
    @product = Product.with_attached_images.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :describle, :list_price, :sell_price, :quantity, :sku, :status, images: [])
  end

  def permission_check!
    if current_user.role != 'admin'
      redirect_to root_path, notice: '無法存取' 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(user)
    if user.role == 'admin'
      admin_root_path
    else
      root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    return @products = Product.available.with_attached_images.sort_by_column(params[:order_by], params[:direction]) if params[:order_by]

    @products = Product.available.with_attached_images.sort_by_created_at
  end

  def show
    @product = Product.with_attached_images.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def sortable(column)
    direction = params[:direction] == 'DESC' ? 'ASC' : 'DESC'
    link_to '價格', order_by: column, direction: direction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def sortable(column)
    direction = params[:direction] == 'DESC' ? 'ASC' : 'DESC'
    link_to t("products.#{column}"), order_by: column, direction: direction
  end

  def cover_image_tag(product, width, height, multiple_image: false)
    if multiple_image
      multiple_cover_image(product, width, height)
    elsif product.images.attached?
      simple_cover_image(product, width, height)
    else
      fake_image(width, height)
    end
  end

  private

  def multiple_cover_image(product, width, height)
    image_tag product.variant(resize_to_fill: ["#{width}", "#{height}"])
  end

  def simple_cover_image(product, width, height)
    image_tag product.images.first.variant(resize_to_fill: ["#{width}", "#{height}"])
  end

  def fake_image(width, height)
    image_tag "https://fakeimg.pl/#{width}x#{height}/?text=upload image!"
  end
end

app/views/admin/products/_form.html.erb
<div>
  <% if product.errors.any? %>
    <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
</div>

<%= form_with model: [:admin, product], local: true do |f| %>
<div>
  <% product.images.each do |image| %>
    <%= cover_image_tag(image, 300, 300, multiple_image: true)%>
    <%= link_to t("products.links.delete_image"), destroy_image_admin_product_path(image.id), method: :delete %>
    <%= f.hidden_field :images, multiple: true, value: image.signed_id %>
  <% end %>
</div>

  <div>
    <%= f.label :images, t("products.upload_images") %>
    <%= f.file_field :images, multiple: true, direct_upload: true %>
  </div>

  <div>
    <%= f.label :name, t("products.page_title.task") %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :list_price, t("products.list_price") %>
    <%= f.number_field :list_price %>
  </div>

  <div>
    <%= f.label :sell_price, t("products.sell_price") %>
    <%= f.number_field :sell_price %>
  </div>

  <div>
    <%= f.label :quantity, t("products.quantity") %>
    <%= f.number_field :quantity %>
  </div>

  <div>
    <%= f.label :sku, t("products.sku") %>
    <%= f.text_field :sku %>
  </div>

    <div>
    <%= f.label :status, t("products.status.status") %>
    <%= f.radio_button :status, 'off_sell', checked: true %>
    <%= f.label :status, t("products.off_sell") %>
    <%= f.radio_button :status, 'on_sell' %>
    <%= f.label :status, t("products.on_sell") %>
    <%= f.radio_button :status, 'restocking' %>
    <%= f.label :status, t("products.restocking") %>
  </div>

  <div>
    <%= f.label :describle, t("products.describle") %>
    <%= f.text_area :describle %>
  </div>

  <div>
    <%= f.submit t("products.links.submit") %>
    <%= link_to t("products.links.cancel"), admin_products_path %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1><%= t("products.page_title.edit") %></h1>

<%= render "form", product: @product %>

app/views/admin/products/index.html.erb
<h1>
  <%= t("products.page_title.list") %>
  <%= link_to t("products.links.add_product"), new_admin_product_path%>
</h1>

<table>
  <thead>
    <tr>
      <th scope='col'><%= t("products.page_title.product") %></th>
      <th scope='col'><%= t("products.page_title.images") %></th>
      <th scope='col'><%= sortable "list_price" %></th>
      <th scope='col'><%= sortable "sell_price" %></th>
      <th scope='col'><%= sortable "quantity" %></th>
      <th scope='col'></th>
      <th scope='col'></th>
      <th scope='col'></th>
    </tr>
  </thead>
  <% @products.with_attached_images.each do |product| %>
    <tbody>
      <td><%= product.name %></td>
      <td><%= cover_image_tag(product, 100, 100) %></td>
      <td><%= product.list_price %></td>
      <td><%= product.sell_price %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to t("products.links.show"), admin_product_path(product) %></td>
      <td><%= link_to t("products.links.edit"), edit_admin_product_path(product) %></td>
      <td><%= link_to t("products.links.delete"), admin_product_path(product), method: :delete, data: { confirm: I18n.t("products.confirms.delete") } %></td>
    </tbody>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<h1><%= t("products.page_title.create") %></h1>

<%= render "form", product: @product %>

app/views/admin/products/show.html.erb
<h3><%= @product.name %></h3>
<table>
  <thead>
  </thead>
  <tbody>
    <tr>
      <td><%= t("prodcuts.image") %></td>
      <% @product.images.each do |image| %>  
        <td><%= cover_image_tag(image, 100, 100, multiple_image: true) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= t("prodcuts.list_price") %></td>
      <td><%= @product.list_price %></td>
    </tr>
    <tr>
      <td><%= t("products.sell_price") %></td>
      <td><%= @product.sell_price %></td>
    </tr>
    <tr>
      <td><%= t("products.quantity") %></td>
      <td><%= @product.quantity %></td>
    </tr>
    <tr>
      <td><%= t("products.sku") %></td>
      <td><%= @product.sku %></td>
    </tr>
    <tr>
      <td><%= t("products.status.title") %></td>
      <td><%= @product.status %></td>
    </tr>
    <tr>
      <td><%= t("products.describle") %></td>
      <td><%= @product.describle %></td>
    </tr>

  </tbody>
  <tfoot>
    <tr>
      <td>
        <%= link_to t("products.links.edit"), edit_admin_product_path(@product) %>
        <%= link_to t("products.links.delete"), admin_product_path(@product), method: :delete, data: { confirm: I18n.t("products.confirms.delete") } %>
        <%= link_to t("products.links.root_page"), admin_products_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= render 'shared/flash' if notice %>
    <%= yield %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/backend/navbar' %>
    <%= render 'shared/flash' if notice %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div>
  <% if product.errors.any? %>
    <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
</div>

<%= form_with model: product, local: true do |f| %>
<div>
  <% if product.images.attached?%>
    <% product.images.each do |image| %>
      <% if image.id.present? %>
        <%= image_tag image %>
        <%= f.hidden_field :images, multiple: true, value: image.signed_id %>
        <%= link_to '刪除圖片', destroy_image_product_path(image.id), method: :delete %>
      <% end %>
    <% end %>
  <% end %>
</div>

  <div>
    <%= f.label :images, '上傳圖檔' %>
    <%= f.file_field :images, multiple: true, direct_upload: true %>
  </div>

  <div>
    <%= f.label :name, '產品名稱' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :list_price, '售價' %>
    <%= f.number_field :list_price %>
  </div>

  <div>
    <%= f.label :sell_price, '特價' %>
    <%= f.number_field :sell_price %>
  </div>

  <div>
    <%= f.label :quantity, '數量' %>
    <%= f.number_field :quantity %>
  </div>

  <div>
    <%= f.label :sku, 'SKU' %>
    <%= f.text_field :sku %>
  </div>

    <div>
    <%= f.label :status, '產品狀態' %>
    <%= f.radio_button :status, 'off_sell', checked: true %>
    <%= f.label :status, '下架' %>
    <%= f.radio_button :status, 'on_sell' %>
    <%= f.label :status, '上架' %>
    <%= f.radio_button :status, 'restocking' %>
    <%= f.label :status, '進貨中' %>
  </div>

  <div>
    <%= f.label :describle, '產品敘述' %>
    <%= f.text_area :describle %>
  </div>

  <div>
    <%= f.submit %>
    <%= link_to '取消', products_path %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1><%= t("products.page_title.list") %></h1>
<table>
  <thead>
    <tr>
      <th scope='col'><%= t("products.page_title.product") %></th>
      <th scope='col'><%= t("products.page_title.images") %></th>
      <th scope='col'><%= sortable "list_price" %></th>
      <th scope='col'><%= sortable "sell_price" %></th>
      <th scope='col'></th>
    </tr>
  </thead>
  <% @products.with_attached_images.each do |product| %>
    <tbody>
      <td><%= product.name %></td>
      <td><%= cover_image_tag(product, 100, 100) %></td>
      <td><%= product.list_price %></td>
      <td><%= product.sell_price %></td>
      <td><%= link_to t("products.links.show"), product_path(product) %></td>
    </tbody>
  <% end %>
</table>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<table>
  <thead>
  </thead>
  <tbody>
    <tr>
      <td><%= t("prodcuts.image") %></td>
      <% @product.images.each do |image| %>  
        <td><%= cover_image_tag(image, 100, 100, multiple_image: true) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= t("products.list_price") %></td>
      <td><%= @product.list_price %></td>
    </tr>
    <tr>
      <td><%= t("products.sell_price") %></td>
      <td><%= @product.sell_price %></td>
    </tr>
    <tr>
      <td><%= t("products.quantity") %></td>
      <td><%= @product.quantity %></td>
    </tr>
    <tr>
      <td><%= t("products.status.title") %></td>
      <td><%= @product.status %></td>
    </tr>
    <tr>
      <td><%= t("products.describle") %></td>
      <td><%= @product.describle %></td>
    </tr>

  </tbody>
  <tfoot>
    <tr>
      <td>
        <%= link_to t("products.links.root_page"), products_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/shared/_flash.html.erb
<% flash.each do |key, value|%>
  <%= value %>
<% end %>

app/views/shared/backend/_navbar.html.erb
<nav>
  <% if current_user %>
    <h1>
      <%= link_to t('products.page_title.company'), root_path %>
      Hello, <%= current_user.username %>! Here is a manager interface.
    </h1>
    <%= link_to t('products.links.to_frontend'), products_path %>
    <%= link_to t('products.links.devise.edit'), edit_user_registration_path %>
    <%= link_to t('products.links.devise.logout'), destroy_user_session_path, method: 'delete' %>
  <% else %>
    <h1>
      <%= link_to t('products.page_title.company'), root_path %>
    </h1>
    <%= link_to t('products.links.devise.sign_up'), new_user_registration_path %>
    <%= link_to t('products.links.devise.login'), new_user_session_path %>
  <% end %>
</nav>

app/views/shared/frontend/_navbar.html.erb
<nav>
  <% if current_user %>
    <h1>
      <%= link_to t('products.page_title.company'), root_path %>
      Hello, <%= current_user.username %>! Here is a Store interface.
    </h1>
    <%= link_to t('products.links.to_backend'), admin_products_path %>
    <%= link_to t('products.links.devise.edit'), edit_user_registration_path %>
    <%= link_to t('products.links.devise.logout'), destroy_user_session_path, method: 'delete' %>
  <% else %>
    <h1>
      <%= link_to t('products.page_title.company'), root_path %>
    </h1>
    <%= link_to t('products.links.devise.sign_up'), new_user_registration_path %>
    <%= link_to t('products.links.devise.login'), new_user_session_path %>
  <% end %>
</nav>